FROM ubuntu:20.04
ENV LANG C.UTF-8

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND noninteractive
ENV HOME /root
WORKDIR $HOME

RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates python3 python3-pip python3-venv ffmpeg libgl1-mesa-dev libglib2.0-0 libsm6 libxrender1 libxext6 nano vim htop && \
  rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/local/bin/pip pip /usr/bin/pip3 1

ENV VIRTUAL_ENV=$HOME/venv_superannotatesdk_dev_env
RUN python -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

COPY . $HOME/superannotate-python-sdk

RUN pip install --no-cache-dir -e superannotate-python-sdk && \
  pip install --no-cache-dir jupyterlab && \
  pip install --no-cache-dir pytest pytest-xdist pytest-timeout && \
  pip install --no-cache-dir coverage pytest-cov && \
  pip install --no-cache-dir pylint pylint-json2html pylint-pytest && \
  pip install --no-cache-dir yapf && \
  pip install --no-cache-dir sphinx sphinx_rtd_theme && \ 
  pip install --no-cache-dir twine && \
  pip install --no-cache-dir xeus-python notebook && \
  rm -rf /root/.cache/pip

CMD ["jupyter", "lab", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''", "--no-browser", "--ip", "0.0.0.0"]